### ISSUE TITLE
Quick c1/c2 Q: on breakout board

### ISSUE THREAD

**Issue by foenixrising** [FujiNetWIFI/atari-sio-breakout#1]
What type and values capacitors (C1/C2)?  Are these only req'd for gaining accurate reading from an oscilloscope/probe or required?

I'd like to break a SIOMIDI interface out, and otherwise use the SIO cable to goto a Fujinet.

Thank you,
Michael

**Comment by mozzwald** [comment]
Capacitors are optional and can be any value needed for the particular application
